---
- src: https://github.com/resmo/ansible-role-ntp
  path: roles
  version: 0.4.0

- src: https://github.com/CSCfi/ansible-role-fgci-install
  path: roles
  version: v1.8.0

# called -2 because it replaces another role called ansible-role-yum-cron
- src: https://github.com/jeffwidman/ansible-yum-cron
  path: roles
  name: ansible-role-yum-cron-2
  version: f58e773036aa9e2baade8c4a33b81be08a232414

- src: https://github.com/CSCfi/ansible-role-users
  path: roles
  version: v1.8.2

- src: https://github.com/jabl/ansible-role-rsyslog
  path: roles
  version: c8df3b8ec9de6659b83c4dd62cf9db0cc87d6798

- src: https://github.com/CSCfi/ansible-role-dhcp_server
  path: roles
  version: v1.0.2

- src: https://github.com/CSCfi/ansible-role-pxe_bootstrap
  path: roles
  version: v1.4.3

- src: https://github.com/CSCfi/ansible-role-squid
  path: roles
  version: v1.3.1

- src: https://github.com/CSCfi/ansible-ferm-firewall
  path: roles
  name: ansible-role-ferm-firewall
  version: v1.2.2

- src: https://github.com/CSCfi/ansible-role-fail2ban
  path: roles
  version: v1.3.0

- src: https://github.com/jabl/ansible-role-slurm
  path: roles
  version: a2d874a98dbe76d093b06031f2058984caf6b838

- src: https://github.com/CSCfi/ansible-role-cvmfs
  path: roles
  version: 0760a16399bbf6b7e4bcb87ba409c8aed38a959a

- src: https://github.com/CSCfi/ansible-aliases
  path: roles
  name: ansible-role-aliases
  version: v1.0.2

- src: https://github.com/jabl/ansible-role-rdma
  path: roles
  version: 00538ee8897d9b9e69fd98062c05483c15a4d2d7

- src: https://github.com/willshersystems/ansible-sshd
  path: roles
  name: ansible-role-sshd
  version: 6f43191418382ed0518f34c166df44de50c44df8

- src: https://github.com/CSCfi/ansible-system-limits
  path: roles
  name: ansible-role-system-limits
  version: v1.1.0

- src: https://github.com/AaltoScienceIT/ansible-role-arc-client
  path: roles
  version: 8e075db2797c5e23979413ba43fb4ddb9aa00b31

- src: https://github.com/CSCfi/ansible-role-yum
  path: roles
  version: v1.5.0

- src: https://github.com/CSCfi/ansible-role-flowdock
  path: roles
  version: v1.3.0

- src: https://github.com/CSCfi/ansible-role-collectd
  path: roles
  version: 84d6e8678a40c4efca7698216b0bf2d2e98c25f6

- src: https://github.com/CSCfi/ansible-role-pxe_config
  path: roles
  version: v1.6.1

- src: https://github.com/CSCfi/ansible-role-dnsmasq
  path: roles
  version: v1.0.1

- src: https://github.com/CSCfi/ansible-role-nis
  path: roles
  version: v1.1.0

- src: https://github.com/CSCfi/ansible-role-nfs
  path: roles
  version: v1.1.0

- src: https://github.com/CSCfi/ansible-role-nfs_mount
  path: roles
  version: v1.3.0

- src: https://github.com/CSCfi/ansible-role-arc-frontend
  path: roles
  version: v1.4.0

- src: https://github.com/CSCfi/ansible-role-fgci-bash
  path: roles
  version: v1.2.1

- src: https://github.com/CSCfi/ansible-role-cuda
  path: roles
  version: v1.6.0

- src: https://github.com/CSCfi/ansible-role-nhc
  path: roles
  version: v1.3.2

- src: https://github.com/CSCfi/ansible-role-nhc-scripts
  path: roles
  version: v1.0.1

- src: https://github.com/CSCfi/ansible-role-dell
  path: roles
  version: v1.1.2

- src: https://github.com/CSCfi/ansible-role-sshd-host-keys
  path: roles
  version: v1.1.0

- src: https://github.com/AaltoScienceIT/ansible-role-smartd
  path: roles
  version: 795823484d7f1aa1fa85db8b8b1f84b0afd7f734

- src: https://github.com/jabl/ansible-role-postfix
  path: roles
  version: 46c6d43a835bdb33de13155692d881ede0581794

- src: https://github.com/CSCfi/ansible-role-fgci-repo
  path: roles
  version: v1.0.0

- src: https://github.com/CSCfi/ansible-role-fgci-login
  path: roles
  version: v1.1.2

- src: https://github.com/mhakala/ansible-role-adauth
  path: roles
  version: 2bdbb3389ac2a163a81e883139088da7e237162c

- src: https://github.com/jabl/ansible-role-pdsh-genders
  path: roles
  version: v1.2.4

- src: https://github.com/CSCfi/ansible-role-serial-console
  path: roles
  version: v1.1.0

- src: https://github.com/cmprescott/ansible-role-autofs
  path: roles
  name: ansible-role-autofs
  version: 1e52d2e57a964345a20ba591bd73f438f2e16576

- src: https://github.com/CSCfi/ansible-nsswitch
  path: roles
  name: ansible-role-nsswitch
  version: v1.0.0

- src: https://github.com/mhakala/ansible-role-lustre_client
  path: roles
  version: 919b7a5640b52e3a0bcc941ad41c64e14f27873d

- src: https://github.com/jabl/ansible-role-pam
  path: roles
  version: v1.0.1

- src: https://github.com/jabl/ansible-role-gitmirror
  path: roles
  version: v1.0.0

- src: https://github.com/mhakala/ansible-role-idmapd
  path: roles
  version: 0b48d86318da6e303e76359a593f5195076f3021

- src: https://github.com/mhakala/ansible-role-samba
  path: roles
  version: 303611d1ff5a4a471128dff485de4fa637a7bee5

- src: https://github.com/jabl/ansible-role-open-vm-tools
  path: roles
  version: v1.0.1

- src: https://github.com/AaltoScienceIT/ansible-systemd-journal
  path: roles
  version: 3b6912f1c030cd555e7d258222a852a89ad7c229
  name: ansible-role-systemd-journal

- src: https://github.com/jabl/ansible-role-hosts-int
  path: roles
  version: v1.0.2

- src: https://github.com/jabl/ansible-role-chrony
  path: roles
  version: 1e7114159f419bbc23fb384d4b5f1e2a9426fd5b

- src: https://github.com/AaltoScienceIT/ansible-lldpd
  path: roles
  version: 659eca372bfb73b79c3152fe29f7b4bf213f893d
  name: ansible-role-lldpd

- src: https://github.com/CSCfi/ansible-role-singularity
  path: roles
  version: v1.0.1

- src: https://github.com/jabl/ansible-role-ohpc-repo
  path: roles
  version: v0.1

- src: https://github.com/jabl/ansible-role-ohpc-setup
  path: roles

- src: https://github.com/jabl/ansible-role-ohpc-finish
  path: roles
